version: '3.2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/usr/share/nginx/html
    ports:
      - 8080:80

  php7:
    image: php:7-fpm
    container_name: php7
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
    expose:
      - "9000"
